GET http://localhost:8080/navio

###
POST http://localhost:8080/navio
Content-Type: application/json

{
    "nome": "Dom Joã VII",
    "ativo": "Não"
}

PATCH http://localhost:8080/navio/9
Content-Type: application/json

{
    "nome": "Remossada IV",
    "ativo": "sim"
}

DELETE http://localhost:8080/navio/9