GET http://localhost:8080/operador

###
POST http://localhost:8080/operador
Content-Type: application/json

{
    "nome": "Uni-z",
    "ativo": "Sim"
}

PATCH http://localhost:8080/operador/6
Content-Type: application/json

{
    "nome": " Albras S/A ",
    "ativo": "sim"
}

DELETE http://localhost:8080/operador/6
