GET http://localhost:8080/porto

###
POST http://localhost:8080/porto
Content-Type: application/json

{
    "nome": " Vila do Conde",
    "ativo": "Sim"
}

PATCH http://localhost:8080/porto/1
Content-Type: application/json

{
    "nome": " Vila do Conde ",
    "ativo": "sim"
}

DELETE http://localhost:8080/porto/1
